import type { SellerLead } from '../types';
import { MOCK_SELLER_LISTINGS } from './listings';

const now = Date.now();
const hrs = (n: number) => new Date(now - n * 3600000).toISOString();

export const MOCK_SELLER_LEADS: SellerLead[] = [
  {
    id: 'sld1',
    listingId: 'sl1',
    listingTitle: MOCK_SELLER_LISTINGS[0].title,
    listingImage: MOCK_SELLER_LISTINGS[0].images[0],
    consumerName: 'Rahul Khanna',
    consumerPhone: '9876512340',
    consumerEmail: 'rahul.khanna@example.com',
    message: 'Interested in this property. Can I visit on Sunday afternoon?',
    status: 'new',
    createdAt: hrs(2),
    updatedAt: hrs(2),
  },
  {
    id: 'sld2',
    listingId: 'sl1',
    listingTitle: MOCK_SELLER_LISTINGS[0].title,
    listingImage: MOCK_SELLER_LISTINGS[0].images[0],
    consumerName: 'Priya Sharma',
    consumerPhone: '9988776655',
    consumerEmail: 'priya.s@example.com',
    message: 'Is the price negotiable? Looking for end-use, family of 4.',
    status: 'contacted',
    createdAt: hrs(8),
    updatedAt: hrs(4),
  },
  {
    id: 'sld3',
    listingId: 'sl2',
    listingTitle: MOCK_SELLER_LISTINGS[1].title,
    listingImage: MOCK_SELLER_LISTINGS[1].images[0],
    consumerName: 'Anand Verma',
    consumerPhone: '9123456789',
    consumerEmail: 'anand.v@example.com',
    message: 'Want a virtual tour first.',
    status: 'visit_booked',
    createdAt: hrs(28),
    updatedAt: hrs(10),
  },
  {
    id: 'sld4',
    listingId: 'sl1',
    listingTitle: MOCK_SELLER_LISTINGS[0].title,
    listingImage: MOCK_SELLER_LISTINGS[0].images[0],
    consumerName: 'Meera Iyer',
    consumerPhone: '9871122334',
    consumerEmail: 'meera.i@example.com',
    status: 'new',
    createdAt: hrs(36),
    updatedAt: hrs(36),
  },
  {
    id: 'sld5',
    listingId: 'sl2',
    listingTitle: MOCK_SELLER_LISTINGS[1].title,
    listingImage: MOCK_SELLER_LISTINGS[1].images[0],
    consumerName: 'Kunal Mehta',
    consumerPhone: '9799887766',
    consumerEmail: 'kunal.m@example.com',
    message: 'Loan eligibility query.',
    status: 'closed_won',
    createdAt: hrs(120),
    updatedAt: hrs(20),
  },
  {
    id: 'sld6',
    listingId: 'sl4',
    listingTitle: MOCK_SELLER_LISTINGS[3].title,
    listingImage: MOCK_SELLER_LISTINGS[3].images[0],
    consumerName: 'Amit Joshi',
    consumerPhone: '9991122334',
    consumerEmail: 'amit.j@example.com',
    status: 'closed_lost',
    createdAt: hrs(720),
    updatedAt: hrs(600),
  },
];
